### PR TITLE
[PR] Multihash initial implementation

### PR DESCRIPTION
**Pull request by LuchoTurtle**
loosely related to #1 

This PR doesn't address #1 but implements a prerequisite of it: Multihash.

I've noticed there wasn't a Dart implementation for Multihash -> https://github.com/multiformats/multihash#implementations, 
which is a shame since Dart is increasingly being used.  

This PR will basically necessitate changing the scope of this repo to a library that **offers Multihash capabilities to Dart** instead of building a CID. We are going to use this to build the CID on a different repo though, for sure :).

It's still in progress because I want to refactor and iron out the package so it offers similar capabilities to https://github.com/multiformats/js-multihash,  https://github.com/multiformats/py-multihash, and https://github.com/multiformats/ex_multihash.

### CODE REVIEW

**Review by nelsonic — CHANGES_REQUESTED** [review]
This belongs over in: https://github.com/dwyl/dart_multihash please see: https://github.com/dwyl/dart_multihash/issues/1 Thanks. 👌

**Comment by LuchoTurtle** [comment]
@nelsonic I guess Signal is not working there but I mentioned in the standup I was wanting to change this repo to be the `multihash` one and I'd eventually create the `cid` on a different one, since it's easier for me to maintain the versioning of the changes made.

Since you already went thru the effort of creating the `multihash` one, I'll find a way of cherry picking these commits to another PR there, np 👍

**Comment by nelsonic** [comment]
You don't have to cherry-pick anything. 
Just merge the two repos: https://stackoverflow.com/a/10548919/1148249
Should take _less_ than 1 minute.

Again, _none_ of this would be required if you followed my ["We Don't _Need_ Multihash" request](https://github.com/dwyl/dart_cid/issues/1#issuecomment-1326475907) ... 😜

**Comment by LuchoTurtle** [comment]
@nelsonic I fail to see why we should merge the two repos, why did you create the other one? No matter, don't worry about it 👍 

> Again, none of this would be required if you followed my https://github.com/dwyl/dart_cid/issues/1#issuecomment-1326475907 ... 😜

As for this, you are right and I'm committed to do overtime so it will even out, I promised ;)

**Pull request closed without merging**
