### PR TITLE
[PR] v0.0.1

### PR DESCRIPTION
**Pull request by LuchoTurtle**
addresses #1 

This PR creates a basic version of that creates a [`cid`](https://docs.ipfs.tech/concepts/content-addressing/#cid-inspector) with [`raw` multicodec](https://github.com/multiformats/multicodec#multicodec-table) and `v1` versioning, akin to what's being made with [dwyl/`cid`](https://github.com/dwyl/cid). 

I've noticed that, unlike Elixir and other languages, there isn't a canonical repo that [allows users to encode their hash strings with whatever codec they want. ](https://github.com/multiformats/multicodec#multicodec-table). Should be a fun task for another day.

This PR has basic testing and mocks [`dwyl/dart_multihash`](https://github.com/dwyl/dart_multihash) library, which is waiting to be published. So `multihash` needs to be published first so I can make use of it before publishing this one. 

It's still in progress, as the README still needs to be written (I don't think there's much need to delve into the topics that are written in [dwyl/`cid`](https://github.com/dwyl/cid), so as to not repeat information. I'll reference it on a "Further reading" basis.

I also want to add property based tests from IPFS, but I still need to figure out how to.

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
`base32` encoding wasn't working at first but mainly because of lack of information. 

I am using the [`base32`](https://pub.dev/packages/base32) package, which allows me to encode it with different standards. Firstly I tried to get it working the same way `dwyl/cid` had it, with the "b" suffix (basically referencing the standard [case-insensitive, no-padding lowercase base32 encoding](https://github.com/multiformats/multibase#multibase-table). 

However, I was using the [IPFS CID inspector ](https://cid.ipfs.tech/#BAFKREIFZJUT3TE2NHYEKKLSS27NH3K72YSCO7Y32KOAO5EEI66WOF36N5E) to check if the output hash was correctly formatted and it wasn't. Turns out that the [`z-base-32`](https://en.wikipedia.org/wiki/Base32#z-base-32) encoding used in the package is confusing, since it uses illegal characters that are not supported for the IPFS convention (only numbers 2-7 are allowed). 

Therefore, to make it IPFS-compatible, I went with the other **default base32 multicodec available**, which was "B" - uppercase base32 with no padding. The package had this option but with padding, so I had to remove that to get it working.

Just wanted to share why I'm not using the default, `base32 lowercase no-padding` approach that was used in `dwyl/cid`.

**Comment by nelsonic** [comment]
Makes sense. Thanks for the update/clarity. 👌

**Comment by LuchoTurtle** [comment]
Added IPFS tests that create a random file and write random strings and check the hash created with `ipfs add file.txt -n --cid-version1`. 

I had a bit of trouble using processes in Dart, I couldn't properly fetch the `stdout` so I had to use a [wrapper](https://pub.dev/packages/test_process) that would allow me to fetch the yielded hash. 

Going to hand it over for review because the generated `cids` so far have all complied, inclusively using the [CID inspector](https://cid.ipfs.tech/#bafkreifzjut3te2nhyekklss27nh3k72ysco7y32koao5eei66wof36n5e). The IPFS tests also pass.

**Comment by LuchoTurtle** [comment]
Marking this as draft and blocked because `multihash`'s package PR needs to be reviewed so I can publish it and use it on this one, instead of mocking. https://github.com/dwyl/dart_multihash/pull/2

**Comment by nelsonic** [comment]
https://github.com/dwyl/dart_multihash/pull/2 merged. :shipit: 
Please proceed. 🙏

**Comment by nelsonic** [comment]
@LuchoTurtle assign when you feel it's reviewable. (Code is already looking good!)

**Comment by LuchoTurtle** [comment]
Just made the needed changes to get this into a reviewable state.
The `dart_multihash` project is used as a dependency now.
I converted the package structure and files for a typical Dart package, following the conventions for publishing. A`--dry-run` does not yield any warnings.
Also added CI that should work once it is merged.

I will update the README with badges once this PR is merged.

**Review by nelsonic — APPROVED** [review]
@LuchoTurtle implementation looks good. 🚀

**Pull request merged**
